[workspace]
members = ["smartpacker", "smartpacker-server"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0"
repository = "https://github.com/niyongsheng/SmartPacker"
authors = ["Nico <niyongsheng@outlook.com>"]

[profile.release]
lto = true
